Activezhao dev
skema-dev/skema-go pull request #5
Opened 2022-04-24 09:50 UTC by activezhao

2022-04-24 10:04 UTC, likezhang-public requested changes

2022-04-24 10:04 UTC, likezhang-public commented on data/manager_test.go
> -            - TestModel1:
这种不要删，这个是数据库初始配置化支持。

2022-04-24 12:20 UTC, activezhao commented on data/manager_test.go
> -            - TestModel1:
OK

2022-04-25 02:55 UTC, likezhang-public approved these changes
lg

2022-04-25 02:55 UTC, merged